id: misconfiguration-found

info:
  name: PhpMyAdmin-Misconfiguration [Detected]
  author: haxshadow
  severity: medium
  description: |
    Detects misconfigured phpMyAdmin installations exposing the setup interface.
    FOFA query: title="phpmyadmin"
  reference:
    - https://fofa.info/result?qbase64=dGl0bGU9InBocG15YWRtaW4i

http:
  - method: GET
    path:
      - "{{BaseURL}}{{paths}}"
    payloads:
      paths:
        - "/phpmyadmin/scripts/setup.php"
        - "/phpMyAdmin/scripts/setup.php"
        - "/_phpmyadmin/scripts/setup.php"
        - "/forum/phpmyadmin/scripts/setup.php"
        - "/php/phpmyadmin/scripts/setup.php"
        - "/typo3/phpmyadmin/scripts/setup.php"
        - "/web/phpmyadmin/scripts/setup.php"
        - "/xampp/phpmyadmin/scripts/setup.php"
        - "/sysadmin/phpMyAdmin/scripts/setup.php"
        - "/phpmyadmin/setup/index.php"
        - "/pma/setup/index.php"
        - "/admin/pma/setup/index.php"
        - "/phpmyadmin/setup/"
        - "/setup/index.php"
        - "/admin/"
        - "/phpMyAdminOLD/setup/index.php"

    stop-at-first-match: true

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "You want to configure phpMyAdmin using web interface"
          - "<title>phpMyAdmin setup</title>"
        condition: or

      - type: status
        status:
          - 200
